services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - horizon-net

  networks:
    horizon-net:
    external: true
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development